# config.yaml

# ===================================================================
# Path Settings
# ===================================================================
path_settings:
  # main.py 的輸出目錄，存放未經處理的原始佈局檔案
  raw_output_directory: "raw_layouts"
  # format_for_ml.py 的輸出目錄，存放格式化後的最終檔案
  ml_ready_output_directory: "dataset_ml_ready"

# ===================================================================
# Generation Task Settings
# ===================================================================
run_settings:
  num_samples_to_generate: 5

# ===================================================================
# Component Type Settings
# ===================================================================
component_types:
  macro:
    proportion: 0.1  # 10% 的隨機元件將是 Macro
    # Macro 的尺寸明顯大於 Standard Cell
    width_range: [80, 200]
    height_range: [80, 200]
    growth_prob_range: [0.7, 0.95] # Macro 依然有較高的生長意願
  std_cell:
    proportion: 0.9  # 90% 的隨機元件將是 Standard Cell
    # Standard Cell 的尺寸較小
    width_range: [10, 30]
    height_range: [10, 30]
    growth_prob_range: [0.1, 0.4] # Standard Cell 生長意願較低

# ===================================================================
# Alignment & Symmetry Settings
# ===================================================================
alignment_settings:
  enable: false
  num_sets:
    type: "randint"
    low: 3
    high: 6
  # 每個集合包含多少個元件
  components_per_set:
    type: "randint"
    low: 2
    high: 4
  # 新增: 0.2 表示 20% 的對齊群組將由 Macro 組成
  macro_proportion: 0.8
  # 對齊群組中的元件尺寸將從上面的 component_types 中讀取
  gap_range: [2, 8]
  # 各種對齊模式的權重，用於隨機選擇
  alignment_mode_weights:
    - { mode: "left", weight: 1 }
    - { mode: "right", weight: 1 }
    - { mode: "top", weight: 1 }
    - { mode: "bottom", weight: 1 }
    - { mode: "h_center", weight: 2 }
    - { mode: "v_center", weight: 2 }

# --- Analog Symmetry Settings ---
analog_symmetry_settings:
  enable: false
  num_groups:
    type: "randint"
    low: 2
    high: 4
  # 新增: 0.3 表示 30% 的對稱群組將由 Macro 組成
  macro_proportion: 0.8
  group_configs:
    - { rects_per_group: 2, group_axis: "vertical", weight: 3 }
    - { rects_per_group: 2, group_axis: "horizontal", weight: 2 }
  # 對稱群組中的元件尺寸將從上面的 component_types 中讀取
  group_gap_range: [4, 10]

# --- Hierarchical Grouping Settings ---
grouping_settings:
  enable: false
  method: "proximity"
  num_groups_to_create:
    type: "randint"
    low: 4
    high: 8
  items_per_group:
    type: "randint"
    low: 2
    high: 4
  # 限制群組搜尋半徑，避免將距離太遠的元件組在一起
  max_search_radius: 150.0

# --- Base Parameters (Fixed values) ---
base_params:
  CANVAS_WIDTH: 1000
  CANVAS_HEIGHT: 1000
  MAX_ITERATIONS: 3000
  GROWTH_STEP: 1
  STAGNATION_LIMIT: 300
  SHAKE_TRIGGER_THRESHOLD: 30
  ROLLBACK_STEPS: 5
  SHAKE_ITERATIONS: 15
  SHAKE_STRENGTH: 1.0
  INFILL_TRIGGER_AFTER_N_SHAKES: 5
  INFILL_COMPONENT_COUNT: 10
  INFILL_GRID_DENSITY: 50
  INFILL_MAX_TRIGGERS: 3
  # 以下兩個參數現在是唯一控制引腳數量的參數
  PIN_DENSITY_K: 0.01
  EDGE_P_MAX: 0.6
  MAX_WIRELENGTH_LIMIT: 500
  # Pin 在邊緣的範圍比例。0.1 表示在離邊緣 10% 的寬度/高度範圍內生成。
  PIN_EDGE_MARGIN_RATIO: 0.1
  # K-最近鄰的 K 值，控制 Netlist 密度
  EDGE_K_NEAREST_NEIGHBORS: 15

# --- Parameters to Randomize ---
randomize_params:
  NUM_RECTANGLES:
    type: "randint"
    low: 230
    high: 230
  TARGET_DENSITY:
    type: "uniform"
    low: 0.75
    high: 0.85
  MAX_ASPECT_RATIO:
    type: "uniform"
    low: 2.0
    high: 4.0
  MACRO_RATIO:
    type: "uniform"
    low: 0.05
    high: 0.20
  MACRO_GROWTH_PROB_RANGE:
    type: "uniform_pair"
    low: [0.7, 0.8]
    high: [0.9, 0.98]
  STD_CELL_GROWTH_PROB_RANGE:
    type: "uniform_pair"
    low: [0.1, 0.2]
    high: [0.4, 0.5]
  RENT_EXPONENT_P:
    type: "uniform"
    low: 0.55
    high: 0.7
  EDGE_DECAY_RATE:
    type: "uniform"
    low: 0.003
    high: 0.008