# config.yaml (增加了 grouping_settings)

# --- Generation Task Settings ---
run_settings:
  num_samples_to_generate: 10
  output_directory: "dataset_align"

# ===================================================================
# Alignment Settings
# ===================================================================
alignment_settings:
  enable: true # 設定為 true 來啟用此功能
  # 要生成多少個對齊的元件集合
  num_sets:
    type: "randint"
    low: 3
    high: 8
  # 每個集合包含多少個元件
  components_per_set:
    type: "randint"
    low: 2
    high: 4
  # 對齊元件的大小範圍
  component_width_range: [20, 50]
  component_height_range: [40, 80]
  # 對齊元件之間的間隙範圍
  gap_range: [5, 10]

# --- Analog Symmetry Settings ---
analog_symmetry_settings:
  enable: true
  num_groups:
    type: "randint"
    low: 4
    high: 8
  group_configs:
    - { rects_per_group: 4, group_axis: "quad", weight: 1 }
    - { rects_per_group: 2, group_axis: "vertical", weight: 3 }
    - { rects_per_group: 2, group_axis: "horizontal", weight: 2 }
    - { rects_per_group: 6, group_axis: "vertical", weight: 1 }
    - { rects_per_group: 4, group_axis: "horizontal", weight: 1 }
  component_width_range: [60, 120]
  component_height_range: [80, 140]
  group_gap_range: [4, 10]
  pins_per_component: [2, 5]

# ===================================================================
# Hierarchical Grouping Settings
# ===================================================================
grouping_settings:
  enable: true # 設定為 true 來啟用此功能
  # 要嘗試建立多少個新的階層式群組
  num_groups_to_create:
    type: "randint"
    low: 3
    high: 6
  # 每個新群組應包含多少個「項目」(項目可以是單一元件或已存在的對稱群組)
  items_per_group:
    type: "randint"
    low: 2
    high: 5
  # 組成群組的方法，目前僅支援 "proximity" (鄰近度)
  method: "proximity"

# --- Base Parameters (Fixed values) ---
base_params:
  CANVAS_WIDTH: 1000
  CANVAS_HEIGHT: 1000
  MAX_ITERATIONS: 3000
  GROWTH_STEP: 1
  STAGNATION_LIMIT: 300
  SHAKE_TRIGGER_THRESHOLD: 30
  ROLLBACK_STEPS: 5
  SHAKE_ITERATIONS: 15
  SHAKE_STRENGTH: 1.0
  INFILL_TRIGGER_AFTER_N_SHAKES: 5
  INFILL_COMPONENT_COUNT: 10
  INFILL_GRID_DENSITY: 50
  INFILL_MAX_TRIGGERS: 3
  PIN_DENSITY_K: 0.01
  EDGE_P_MAX: 0.6
  MAX_WIRELENGTH_LIMIT: 500

# --- Parameters to Randomize ---
randomize_params:
  NUM_RECTANGLES:
    type: "randint"
    low: 180
    high: 250
  TARGET_DENSITY:
    type: "uniform"
    low: 0.75
    high: 0.85
  MAX_ASPECT_RATIO:
    type: "uniform"
    low: 2.0
    high: 4.0
  MACRO_RATIO:
    type: "uniform"
    low: 0.05
    high: 0.20
  MACRO_GROWTH_PROB_RANGE:
    type: "uniform_pair"
    low: [0.7, 0.8]
    high: [0.9, 0.98]
  STD_CELL_GROWTH_PROB_RANGE:
    type: "uniform_pair"
    low: [0.1, 0.2]
    high: [0.4, 0.5]
  RENT_EXPONENT_P:
    type: "uniform"
    low: 0.55
    high: 0.7
  EDGE_DECAY_RATE:
    type: "uniform"
    low: 0.003
    high: 0.008